
import React, { useState } from 'react';
import { BudgetRequest, Paystub, ClientCompany, Employee } from '../types';

interface AdminDashboardProps {
  requests: BudgetRequest[];
  companies: ClientCompany[];
  employees: Employee[];
  
  onAddCompany: (company: ClientCompany) => void;
  onEditCompany: (company: ClientCompany) => void;
  onDeleteCompany: (id: string) => void;

  onAddEmployee: (employee: Employee) => void;
  onEditEmployee: (employee: Employee) => void;
  onDeleteEmployee: (id: string) => void;

  onAddPaystub: (paystub: Paystub, file: File | null) => Promise<void>;

  onUpdateRequestStatus: (id: string, status: 'pending' | 'contacted') => void;
  onDeleteRequest: (id: string) => void;

  currentUserRole: 'admin' | 'master_admin';
  currentUserId: string;
  onDeleteAdmin: (id: string) => void;

  onUpdatePassword: (newPass: string) => void;
}

const AdminDashboard: React.FC<AdminDashboardProps> = ({ 
    requests, 
    companies, 
    employees,
    onAddCompany, 
    onEditCompany, 
    onDeleteCompany,
    onAddEmployee,
    onEditEmployee,
    onDeleteEmployee,
    onAddPaystub,
    onUpdateRequestStatus,
    onDeleteRequest,
    currentUserRole,
    currentUserId,
    onDeleteAdmin,
    onUpdatePassword
}) => {
  // Initialize active tab based on role. Regular admins don't see 'requests' or 'admins'.
  const [activeTab, setActiveTab] = useState<'requests' | 'clients' | 'paystubs' | 'admins'>(() => {
      return currentUserRole === 'master_admin' ? 'requests' : 'clients';
  });

  // --- Requests State ---
  const [selectedRequest, setSelectedRequest] = useState<BudgetRequest | null>(null);

  // --- Company Management State ---
  const [showCompanyForm, setShowCompanyForm] = useState(false);
  const [editingCompany, setEditingCompany] = useState<ClientCompany | null>(null);
  const [companyForm, setCompanyForm] = useState({ name: '', cnpj: '' });

  // --- Employee Management State ---
  const [managingEmployeesForCompanyId, setManagingEmployeesForCompanyId] = useState<string | null>(null);
  const [showEmployeeForm, setShowEmployeeForm] = useState(false);
  const [editingEmployee, setEditingEmployee] = useState<Employee | null>(null);
  const [employeeForm, setEmployeeForm] = useState({ name: '', username: '', password: '' });

  // --- Admin Management State (Master Only) ---
  const [showAdminForm, setShowAdminForm] = useState(false);
  const [editingAdmin, setEditingAdmin] = useState<Employee | null>(null);
  const [adminForm, setAdminForm] = useState({ name: '', username: '', password: '', role: 'admin' });

  // --- Password Update State ---
  const [showPasswordModal, setShowPasswordModal] = useState(false);
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');

  // --- Paystub Form State ---
  const [stubCompanyId, setStubCompanyId] = useState('');
  const [stubEmployeeId, setStubEmployeeId] = useState('');
  const [title, setTitle] = useState('Folha Pagamento');
  const [month, setMonth] = useState('Janeiro');
  const [year, setYear] = useState(2024);
  const [value, setValue] = useState('');
  const [paymentDate, setPaymentDate] = useState('');
  const [pdfFile, setPdfFile] = useState<File | null>(null);
  const [isUploading, setIsUploading] = useState(false);

  // --- Delete Confirmation State ---
  const [deleteConfirmation, setDeleteConfirmation] = useState<{
      type: 'company' | 'employee' | 'request' | 'admin';
      id: string;
      name?: string;
  } | null>(null);


  // ---------------- Handlers: Company ----------------
  const handleCompanySubmit = (e: React.FormEvent) => {
      e.preventDefault();
      if (editingCompany) {
          onEditCompany({
              ...editingCompany,
              name: companyForm.name,
              cnpj: companyForm.cnpj
          });
          setEditingCompany(null);
      } else {
          onAddCompany({
              id: '', // Generated by DB
              name: companyForm.name,
              cnpj: companyForm.cnpj,
              contractStatus: 'active',
          });
      }
      setCompanyForm({ name: '', cnpj: '' });
      setShowCompanyForm(false);
  };

  const startEditCompany = (company: ClientCompany) => {
      setEditingCompany(company);
      setCompanyForm({ name: company.name, cnpj: company.cnpj });
      setShowCompanyForm(true);
  };

  const requestDeleteCompany = (company: ClientCompany) => {
      setDeleteConfirmation({ type: 'company', id: company.id, name: company.name });
  };

  // ---------------- Handlers: Employee ----------------
  const openEmployeeManager = (companyId: string) => {
      setManagingEmployeesForCompanyId(companyId);
  };

  const closeEmployeeManager = () => {
      setManagingEmployeesForCompanyId(null);
  };

  const handleEmployeeSubmit = (e: React.FormEvent) => {
      e.preventDefault();
      if (!managingEmployeesForCompanyId) return;

      if (editingEmployee) {
          onEditEmployee({
              ...editingEmployee,
              name: employeeForm.name,
              username: employeeForm.username,
              password: employeeForm.password
          });
          setEditingEmployee(null);
      } else {
          onAddEmployee({
              id: '', // Generated by DB
              companyId: managingEmployeesForCompanyId,
              name: employeeForm.name,
              username: employeeForm.username,
              password: employeeForm.password,
              role: 'employee'
          });
      }
      setEmployeeForm({ name: '', username: '', password: '' });
      setShowEmployeeForm(false);
  };

  const startEditEmployee = (employee: Employee) => {
      setEditingEmployee(employee);
      setEmployeeForm({ 
          name: employee.name, 
          username: employee.username, 
          password: employee.password 
      });
      setShowEmployeeForm(true);
  };

  const requestDeleteEmployee = (employee: Employee) => {
      setDeleteConfirmation({ type: 'employee', id: employee.id, name: employee.name });
  };

  // ---------------- Handlers: Admins (Master Only) ----------------
  const handleAdminSubmit = (e: React.FormEvent) => {
      e.preventDefault();
      
      const roleToSave = (adminForm.role === 'master_admin' || adminForm.role === 'admin') ? adminForm.role : 'admin';

      if (editingAdmin) {
          // Update Existing Admin
          onEditEmployee({
              id: editingAdmin.id,
              companyId: editingAdmin.companyId,
              name: adminForm.name,
              username: adminForm.username,
              password: adminForm.password,
              role: roleToSave // Use role from form
          });
          setEditingAdmin(null);
      } else {
          // Create New Admin
          const ADMIN_COMPANY_ID = '00000000-0000-0000-0000-000000000000';
          onAddEmployee({
              id: '',
              companyId: ADMIN_COMPANY_ID,
              name: adminForm.name,
              username: adminForm.username,
              password: adminForm.password,
              role: roleToSave // Use role from form
          });
      }

      setAdminForm({ name: '', username: '', password: '', role: 'admin' });
      setShowAdminForm(false);
  };

  const startEditAdmin = (admin: Employee) => {
      setEditingAdmin(admin);
      setAdminForm({
          name: admin.name,
          username: admin.username,
          password: admin.password,
          role: (admin.role === 'master_admin' ? 'master_admin' : 'admin')
      });
      setShowAdminForm(true);
  }

  const requestDeleteAdmin = (admin: Employee) => {
      setDeleteConfirmation({ type: 'admin', id: admin.id, name: admin.name });
  };


  // ---------------- Handlers: Paystub ----------------
  const handlePaystubSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!stubEmployeeId) {
        alert("Selecione um funcionário.");
        return;
    }
    
    setIsUploading(true);
    try {
        const newPaystub: Paystub = {
            id: '', // DB will generate
            employeeId: stubEmployeeId,
            title: title,
            month,
            year,
            value: Number(value),
            paymentDate: paymentDate || new Date().toLocaleDateString('pt-BR'),
            pdfUrl: '' // handled in App.tsx
        };

        await onAddPaystub(newPaystub, pdfFile);
        alert('Documento adicionado com sucesso!');
        
        setValue('');
        setPdfFile(null);
    } catch (err) {
        alert('Erro ao fazer upload do documento.');
        console.error(err);
    } finally {
        setIsUploading(false);
    }
  };

  // ---------------- Handlers: Delete Confirmation ----------------
  const handleConfirmDelete = () => {
      if (!deleteConfirmation) return;

      switch (deleteConfirmation.type) {
          case 'company':
              onDeleteCompany(deleteConfirmation.id);
              break;
          case 'employee':
              onDeleteEmployee(deleteConfirmation.id);
              break;
          case 'admin':
              onDeleteAdmin(deleteConfirmation.id);
              break;
          case 'request':
              onDeleteRequest(deleteConfirmation.id);
              setSelectedRequest(null); // Close details modal if open
              break;
      }
      setDeleteConfirmation(null);
  };

  const handleChangePasswordSubmit = (e: React.FormEvent) => {
      e.preventDefault();
      if (newPassword !== confirmPassword) {
          alert("As senhas não coincidem.");
          return;
      }
      onUpdatePassword(newPassword);
      setNewPassword('');
      setConfirmPassword('');
      setShowPasswordModal(false);
  };

  // Filter employees for dropdown
  const filteredEmployees = employees.filter(e => e.companyId === stubCompanyId);

  // Filter admins for Master Admin tab
  const adminUsers = employees.filter(e => e.role === 'admin' || e.role === 'master_admin');

  return (
    <div className="bg-agr-gray min-h-screen pb-20">
      <div className="bg-agr-dark pb-32">
        <header className="py-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
           <div className="flex flex-col md:flex-row items-center justify-between gap-4">
               <div className="flex items-center gap-4">
                   <div className="w-16 h-16 rounded-full bg-red-900 flex items-center justify-center border-2 border-red-500">
                        <i className="fas fa-user-shield text-3xl text-gray-300"></i>
                   </div>
                   <div>
                       <h1 className="text-3xl font-bold text-white">Painel Administrativo</h1>
                       <div className="flex items-center gap-3">
                           <p className="text-red-500 font-medium">
                               {currentUserRole === 'master_admin' ? 'Administrador Master' : 'Gestão Geral'}
                           </p>
                           <button 
                             onClick={() => setShowPasswordModal(true)}
                             className="text-xs bg-gray-700 hover:bg-gray-600 px-2 py-1 rounded text-gray-300"
                           >
                               Trocar Senha
                           </button>
                       </div>
                   </div>
               </div>
               
               <div className="flex space-x-2 overflow-x-auto">
                   {currentUserRole === 'master_admin' && (
                       <button 
                         onClick={() => setActiveTab('requests')}
                         className={`px-4 py-2 rounded-lg font-bold transition-all whitespace-nowrap ${activeTab === 'requests' ? 'bg-green-600 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}
                       >
                           Orçamentos
                       </button>
                   )}
                   <button 
                     onClick={() => setActiveTab('clients')}
                     className={`px-4 py-2 rounded-lg font-bold transition-all whitespace-nowrap ${activeTab === 'clients' ? 'bg-green-600 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}
                   >
                       Empresas & Funcionários
                   </button>
                   <button 
                     onClick={() => setActiveTab('paystubs')}
                     className={`px-4 py-2 rounded-lg font-bold transition-all whitespace-nowrap ${activeTab === 'paystubs' ? 'bg-green-600 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}
                   >
                       Upload Documentos
                   </button>
                   {currentUserRole === 'master_admin' && (
                       <button 
                         onClick={() => setActiveTab('admins')}
                         className={`px-4 py-2 rounded-lg font-bold transition-all whitespace-nowrap ${activeTab === 'admins' ? 'bg-purple-600 text-white' : 'bg-gray-800 text-gray-400 hover:bg-gray-700'}`}
                       >
                           Administradores
                       </button>
                   )}
               </div>
           </div>
        </header>
      </div>

      <main className="-mt-24 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Tab Content: Requests (Master Admin Only) */}
        {activeTab === 'requests' && currentUserRole === 'master_admin' && (
            <div className="bg-gray-800 rounded-lg shadow-xl border border-gray-700 overflow-hidden">
                <div className="px-6 py-4 border-b border-gray-700 bg-gray-900/50 flex justify-between items-center">
                    <h3 className="text-xl font-bold text-white">Solicitações de Orçamento</h3>
                </div>
                <div className="overflow-x-auto">
                    <table className="w-full text-left text-gray-400">
                        <thead className="bg-gray-900 text-gray-200 uppercase text-xs">
                            <tr>
                                <th className="px-6 py-3">Nome</th>
                                <th className="px-6 py-3">Email</th>
                                <th className="px-6 py-3">Mensagem (Resumo)</th>
                                <th className="px-6 py-3">Data</th>
                                <th className="px-6 py-3">Status</th>
                                <th className="px-6 py-3 text-right">Ações</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-700">
                            {requests.length === 0 ? (
                                <tr>
                                    <td colSpan={6} className="px-6 py-8 text-center">Nenhuma solicitação recebida.</td>
                                </tr>
                            ) : (
                                requests.map((req) => (
                                    <tr key={req.id} className="hover:bg-gray-700/50">
                                        <td className="px-6 py-4 font-medium text-white">{req.name}</td>
                                        <td className="px-6 py-4">{req.email}</td>
                                        <td className="px-6 py-4 truncate max-w-xs">{req.message.substring(0, 40)}...</td>
                                        <td className="px-6 py-4">{req.date}</td>
                                        <td className="px-6 py-4">
                                            <span className={`px-2 py-1 rounded-full text-xs ${req.status === 'pending' ? 'bg-yellow-900/50 text-yellow-300' : 'bg-green-900/50 text-green-300'}`}>
                                                {req.status === 'pending' ? 'Pendente' : 'Concluído'}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-right flex justify-end gap-2">
                                            <button 
                                                onClick={() => setSelectedRequest(req)}
                                                className="bg-blue-600 hover:bg-blue-500 text-white px-3 py-1 rounded text-xs font-medium"
                                                title="Ver Detalhes"
                                            >
                                                Ver Detalhes
                                            </button>
                                            <button 
                                                onClick={() => setDeleteConfirmation({ type: 'request', id: req.id, name: 'Solicitação de ' + req.name })}
                                                className="bg-red-600 hover:bg-red-500 text-white px-3 py-1 rounded text-xs font-medium"
                                                title="Excluir"
                                            >
                                                <i className="fas fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>

                {/* Request Details Modal */}
                {selectedRequest && (
                    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
                        <div className="bg-gray-800 rounded-lg shadow-2xl border border-gray-600 w-full max-w-2xl animate-fade-in">
                            <div className="px-6 py-4 border-b border-gray-700 bg-gray-900 rounded-t-lg flex justify-between items-center">
                                <h3 className="text-xl font-bold text-white">Detalhes da Solicitação</h3>
                                <button onClick={() => setSelectedRequest(null)} className="text-gray-400 hover:text-white">
                                    <i className="fas fa-times text-xl"></i>
                                </button>
                            </div>
                            <div className="p-6 space-y-4 text-gray-300">
                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <p className="text-sm text-gray-500">Solicitante</p>
                                        <p className="font-bold text-white text-lg">{selectedRequest.name}</p>
                                    </div>
                                    <div>
                                        <p className="text-sm text-gray-500">Data</p>
                                        <p className="text-white">{selectedRequest.date}</p>
                                    </div>
                                    <div className="col-span-2">
                                         <p className="text-sm text-gray-500">Contato</p>
                                         <p className="text-white">{selectedRequest.email}</p>
                                    </div>
                                </div>
                                
                                <div className="bg-gray-700/50 p-4 rounded border border-gray-600">
                                    <p className="text-sm text-gray-500 mb-2">Mensagem / Descrição</p>
                                    <p className="text-white whitespace-pre-wrap leading-relaxed">{selectedRequest.message}</p>
                                </div>
                                
                                <div className="flex justify-between items-center pt-4 border-t border-gray-700 mt-4">
                                    <div className="flex gap-3">
                                        <button 
                                            onClick={() => {
                                                const newStatus = selectedRequest.status === 'pending' ? 'contacted' : 'pending';
                                                onUpdateRequestStatus(selectedRequest.id, newStatus);
                                                setSelectedRequest({...selectedRequest, status: newStatus});
                                            }}
                                            className={`px-4 py-2 rounded font-bold text-white transition-colors ${selectedRequest.status === 'pending' ? 'bg-green-600 hover:bg-green-500' : 'bg-yellow-600 hover:bg-yellow-500'}`}
                                        >
                                            <i className={`fas ${selectedRequest.status === 'pending' ? 'fa-check' : 'fa-undo'} mr-2`}></i>
                                            {selectedRequest.status === 'pending' ? 'Marcar como Concluído' : 'Reabrir Solicitação'}
                                        </button>
                                        
                                        <button 
                                            onClick={() => setDeleteConfirmation({ type: 'request', id: selectedRequest.id, name: 'Solicitação de ' + selectedRequest.name })}
                                            className="px-4 py-2 rounded bg-red-900/50 text-red-300 border border-red-800 hover:bg-red-800 transition-colors"
                                        >
                                            <i className="fas fa-trash mr-2"></i> Excluir
                                        </button>
                                    </div>
                                    <button 
                                        onClick={() => setSelectedRequest(null)}
                                        className="px-4 py-2 rounded bg-gray-700 text-gray-300 hover:bg-gray-600 transition-colors"
                                    >
                                        Fechar
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                )}
            </div>
        )}

        {/* Tab Content: Clients & Employees */}
        {activeTab === 'clients' && (
             <div className="space-y-6">
                 {/* Company List */}
                 {!managingEmployeesForCompanyId ? (
                     <div className="bg-gray-800 rounded-lg shadow-xl border border-gray-700 overflow-hidden">
                        <div className="px-6 py-4 border-b border-gray-700 bg-gray-900/50 flex justify-between items-center">
                            <h3 className="text-xl font-bold text-white">Empresas Parceiras</h3>
                            <button 
                                onClick={() => {
                                    setEditingCompany(null);
                                    setCompanyForm({ name: '', cnpj: '' });
                                    setShowCompanyForm(true);
                                }}
                                className="bg-green-600 hover:bg-green-500 text-white px-3 py-1 rounded text-sm font-bold shadow-lg"
                            >
                                <i className="fas fa-plus mr-2"></i> Nova Empresa
                            </button>
                        </div>
                        <div className="overflow-x-auto">
                            <table className="w-full text-left text-gray-400">
                                <thead className="bg-gray-900 text-gray-200 uppercase text-xs">
                                    <tr>
                                        <th className="px-6 py-3">Empresa</th>
                                        <th className="px-6 py-3">CNPJ</th>
                                        <th className="px-6 py-3">Funcionários</th>
                                        <th className="px-6 py-3 text-right">Ações</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-gray-700">
                                     {companies.filter(c => c.id !== '00000000-0000-0000-0000-000000000000').map((company) => {
                                         const empCount = employees.filter(e => e.companyId === company.id).length;
                                         return (
                                            <tr key={company.id} className="hover:bg-gray-700/50">
                                                <td className="px-6 py-4 font-medium text-white flex items-center gap-3">
                                                    <div className="w-8 h-8 rounded bg-gray-600 flex items-center justify-center">
                                                        <i className="fas fa-building text-white"></i>
                                                    </div>
                                                    {company.name}
                                                </td>
                                                <td className="px-6 py-4">{company.cnpj}</td>
                                                <td className="px-6 py-4">
                                                    <button 
                                                        onClick={() => openEmployeeManager(company.id)}
                                                        className="bg-blue-900/50 text-blue-300 hover:bg-blue-800 px-3 py-1 rounded text-xs border border-blue-700"
                                                    >
                                                        <i className="fas fa-users mr-1"></i> Gerenciar ({empCount})
                                                    </button>
                                                </td>
                                                <td className="px-6 py-4 text-right">
                                                    <button 
                                                        onClick={() => startEditCompany(company)}
                                                        className="text-gray-400 hover:text-white mr-3" 
                                                        title="Editar Empresa"
                                                    >
                                                        <i className="fas fa-edit"></i>
                                                    </button>
                                                    <button 
                                                        onClick={() => requestDeleteCompany(company)}
                                                        className="text-red-400 hover:text-red-300" 
                                                        title="Excluir Empresa"
                                                    >
                                                        <i className="fas fa-trash"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                         );
                                     })}
                                </tbody>
                            </table>
                        </div>
                     </div>
                 ) : (
                     // Employee Manager View
                     <div className="bg-gray-800 rounded-lg shadow-xl border border-gray-700 overflow-hidden animate-fade-in">
                        <div className="px-6 py-4 border-b border-gray-700 bg-gray-900/50 flex justify-between items-center">
                            <div className="flex items-center gap-4">
                                <button onClick={closeEmployeeManager} className="text-gray-400 hover:text-white">
                                    <i className="fas fa-arrow-left"></i> Voltar
                                </button>
                                <h3 className="text-xl font-bold text-white">
                                    Funcionários: <span className="text-green-500">{companies.find(c => c.id === managingEmployeesForCompanyId)?.name}</span>
                                </h3>
                            </div>
                            <button 
                                onClick={() => {
                                    setEditingEmployee(null);
                                    setEmployeeForm({ name: '', username: '', password: '' });
                                    setShowEmployeeForm(true);
                                }}
                                className="bg-blue-600 hover:bg-blue-500 text-white px-3 py-1 rounded text-sm font-bold shadow-lg"
                            >
                                <i className="fas fa-user-plus mr-2"></i> Novo Funcionário
                            </button>
                        </div>
                        <div className="overflow-x-auto">
                            <table className="w-full text-left text-gray-400">
                                <thead className="bg-gray-900 text-gray-200 uppercase text-xs">
                                    <tr>
                                        <th className="px-6 py-3">Nome</th>
                                        <th className="px-6 py-3">Usuário (Login)</th>
                                        <th className="px-6 py-3">Senha</th>
                                        <th className="px-6 py-3 text-right">Ações</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-gray-700">
                                     {employees.filter(e => e.companyId === managingEmployeesForCompanyId).map((emp) => (
                                        <tr key={emp.id} className="hover:bg-gray-700/50">
                                            <td className="px-6 py-4 font-medium text-white">{emp.name}</td>
                                            <td className="px-6 py-4">{emp.username}</td>
                                            <td className="px-6 py-4 font-mono">****</td>
                                            <td className="px-6 py-4 text-right">
                                                <button 
                                                    onClick={() => startEditEmployee(emp)}
                                                    className="text-gray-400 hover:text-white mr-3" 
                                                    title="Editar"
                                                >
                                                    <i className="fas fa-edit"></i>
                                                </button>
                                                <button 
                                                    onClick={() => requestDeleteEmployee(emp)}
                                                    className="text-red-400 hover:text-red-300" 
                                                    title="Excluir"
                                                >
                                                    <i className="fas fa-trash"></i>
                                                </button>
                                            </td>
                                        </tr>
                                     ))}
                                     {employees.filter(e => e.companyId === managingEmployeesForCompanyId).length === 0 && (
                                         <tr>
                                             <td colSpan={4} className="px-6 py-8 text-center text-gray-500">
                                                 Nenhum funcionário cadastrado nesta empresa.
                                             </td>
                                         </tr>
                                     )}
                                </tbody>
                            </table>
                        </div>
                     </div>
                 )}

                 {/* Modal: Company Form */}
                 {showCompanyForm && (
                     <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
                         <div className="bg-gray-800 rounded-lg shadow-2xl border border-gray-600 w-full max-w-md">
                             <div className="px-6 py-4 border-b border-gray-700 bg-gray-900 rounded-t-lg">
                                 <h3 className="text-xl font-bold text-white">
                                     {editingCompany ? 'Editar Empresa' : 'Adicionar Nova Empresa'}
                                 </h3>
                             </div>
                             <form onSubmit={handleCompanySubmit} className="p-6 space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-400 mb-1">Nome da Empresa</label>
                                    <input 
                                        type="text" 
                                        required
                                        className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                        value={companyForm.name}
                                        onChange={(e) => setCompanyForm({...companyForm, name: e.target.value})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-400 mb-1">CNPJ</label>
                                    <input 
                                        type="text" 
                                        required
                                        className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                        value={companyForm.cnpj}
                                        onChange={(e) => setCompanyForm({...companyForm, cnpj: e.target.value})}
                                    />
                                </div>
                                 <div className="flex justify-end gap-3 mt-6">
                                     <button 
                                        type="button" 
                                        onClick={() => setShowCompanyForm(false)}
                                        className="px-4 py-2 rounded bg-gray-700 text-gray-300 hover:bg-gray-600"
                                     >
                                         Cancelar
                                     </button>
                                     <button type="submit" className="px-4 py-2 rounded bg-green-600 text-white font-bold hover:bg-green-500">Salvar</button>
                                 </div>
                             </form>
                         </div>
                     </div>
                 )}

                 {/* Modal: Employee Form */}
                 {showEmployeeForm && (
                     <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
                         <div className="bg-gray-800 rounded-lg shadow-2xl border border-gray-600 w-full max-w-md">
                             <div className="px-6 py-4 border-b border-gray-700 bg-gray-900 rounded-t-lg">
                                 <h3 className="text-xl font-bold text-white">
                                     {editingEmployee ? 'Editar Funcionário' : 'Novo Funcionário'}
                                 </h3>
                             </div>
                             <form onSubmit={handleEmployeeSubmit} className="p-6 space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-400 mb-1">Nome Completo</label>
                                    <input 
                                        type="text" 
                                        required
                                        className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                        value={employeeForm.name}
                                        onChange={(e) => setEmployeeForm({...employeeForm, name: e.target.value})}
                                    />
                                </div>
                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-sm font-medium text-gray-400 mb-1">Usuário (Login)</label>
                                        <input 
                                            type="text" 
                                            required
                                            className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                            value={employeeForm.username}
                                            onChange={(e) => setEmployeeForm({...employeeForm, username: e.target.value})}
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium text-gray-400 mb-1">Senha</label>
                                        <input 
                                            type="text" 
                                            required
                                            className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                            value={employeeForm.password}
                                            onChange={(e) => setEmployeeForm({...employeeForm, password: e.target.value})}
                                        />
                                    </div>
                                </div>
                                 <div className="flex justify-end gap-3 mt-6">
                                     <button 
                                        type="button" 
                                        onClick={() => setShowEmployeeForm(false)}
                                        className="px-4 py-2 rounded bg-gray-700 text-gray-300 hover:bg-gray-600"
                                     >
                                         Cancelar
                                     </button>
                                     <button type="submit" className="px-4 py-2 rounded bg-green-600 text-white font-bold hover:bg-green-500">Salvar</button>
                                 </div>
                             </form>
                         </div>
                     </div>
                 )}
             </div>
        )}

        {/* Tab Content: Paystubs (Upload) */}
        {activeTab === 'paystubs' && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                 <div className="md:col-span-1 bg-gray-800 rounded-lg shadow-xl border border-gray-700 p-6">
                     <h3 className="text-xl font-bold text-white mb-6 border-b border-gray-700 pb-2">Upload de Contracheque</h3>
                     <form onSubmit={handlePaystubSubmit} className="space-y-4">
                         <div>
                             <label className="block text-sm font-medium text-gray-400 mb-1">1. Selecione a Empresa</label>
                             <select 
                               value={stubCompanyId}
                               onChange={(e) => {
                                   setStubCompanyId(e.target.value);
                                   setStubEmployeeId(''); // Reset employee when company changes
                               }}
                               className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white focus:ring-green-500 focus:border-green-500"
                               required
                             >
                                 <option value="">Selecione...</option>
                                 {companies.filter(c => c.id !== '00000000-0000-0000-0000-000000000000').map(c => (
                                     <option key={c.id} value={c.id}>{c.name}</option>
                                 ))}
                             </select>
                         </div>

                         <div>
                             <label className="block text-sm font-medium text-gray-400 mb-1">2. Selecione o Funcionário</label>
                             <select 
                               value={stubEmployeeId}
                               onChange={(e) => setStubEmployeeId(e.target.value)}
                               className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white focus:ring-green-500 focus:border-green-500"
                               required
                               disabled={!stubCompanyId}
                             >
                                 <option value="">Selecione...</option>
                                 {filteredEmployees.map(e => (
                                     <option key={e.id} value={e.id}>{e.name} ({e.username})</option>
                                 ))}
                             </select>
                         </div>

                         <div className="border-t border-gray-700 pt-4"></div>

                         <div>
                             <label className="block text-sm font-medium text-gray-400 mb-1">Título</label>
                             <input 
                                type="text" 
                                value={title} 
                                onChange={(e) => setTitle(e.target.value)}
                                className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                             />
                         </div>
                         
                         <div className="grid grid-cols-2 gap-4">
                             <div>
                                 <label className="block text-sm font-medium text-gray-400 mb-1">Mês</label>
                                 <select 
                                    value={month}
                                    onChange={(e) => setMonth(e.target.value)}
                                    className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                 >
                                     {['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'].map(m => (
                                         <option key={m} value={m}>{m}</option>
                                     ))}
                                 </select>
                             </div>
                             <div>
                                 <label className="block text-sm font-medium text-gray-400 mb-1">Ano</label>
                                 <input 
                                    type="number" 
                                    value={year} 
                                    onChange={(e) => setYear(Number(e.target.value))}
                                    className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                 />
                             </div>
                         </div>

                         <div>
                             <label className="block text-sm font-medium text-gray-400 mb-1">Data Pagamento</label>
                             <input 
                                type="date" 
                                value={paymentDate} 
                                onChange={(e) => setPaymentDate(e.target.value)}
                                className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                             />
                         </div>

                         <div>
                             <label className="block text-sm font-bold text-green-400 mb-1">Valor Líquido (R$)</label>
                             <input 
                                type="number" 
                                value={value} 
                                onChange={(e) => setValue(e.target.value)}
                                required
                                className="w-full bg-gray-700 border border-green-600 rounded p-2 text-white font-bold"
                                placeholder="0.00"
                             />
                         </div>

                         <div>
                             <label className="block text-sm font-medium text-gray-400 mb-1">Arquivo PDF</label>
                             <input 
                                type="file" 
                                accept="application/pdf"
                                onChange={(e) => setPdfFile(e.target.files ? e.target.files[0] : null)}
                                className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-gray-300 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-green-600 file:text-white hover:file:bg-green-700"
                             />
                         </div>

                         <button 
                            type="submit" 
                            disabled={isUploading}
                            className={`w-full font-bold py-3 rounded-lg shadow-lg transition-all mt-4 ${isUploading ? 'bg-gray-600 cursor-not-allowed' : 'bg-green-600 hover:bg-green-500 text-white'}`}
                        >
                             {isUploading ? 'Enviando...' : 'ENVIAR'}
                         </button>
                     </form>
                 </div>

                 <div className="md:col-span-2 bg-gray-800 rounded-lg shadow-xl border border-gray-700 p-6 flex items-center justify-center text-gray-500 flex-col">
                     <i className="fas fa-file-invoice-dollar text-6xl mb-4 text-gray-700"></i>
                     <h4 className="text-xl font-semibold mb-2 text-gray-300">Central de Upload Individual</h4>
                     <p className="text-center max-w-md">
                         Selecione a empresa e o funcionário específico para vincular o contracheque.
                         O funcionário terá acesso a este documento através do seu painel pessoal.
                     </p>
                 </div>
            </div>
        )}

        {/* Tab Content: Administrators (Master Only) */}
        {activeTab === 'admins' && currentUserRole === 'master_admin' && (
             <div className="space-y-6">
                 <div className="bg-gray-800 rounded-lg shadow-xl border border-gray-700 overflow-hidden">
                    <div className="px-6 py-4 border-b border-gray-700 bg-gray-900/50 flex justify-between items-center">
                        <h3 className="text-xl font-bold text-white">Administradores do Sistema</h3>
                        <button 
                            onClick={() => {
                                setEditingAdmin(null);
                                setAdminForm({ name: '', username: '', password: '', role: 'admin' });
                                setShowAdminForm(true);
                            }}
                            className="bg-purple-600 hover:bg-purple-500 text-white px-3 py-1 rounded text-sm font-bold shadow-lg"
                        >
                            <i className="fas fa-user-plus mr-2"></i> Novo Admin
                        </button>
                    </div>
                    <div className="overflow-x-auto">
                        <table className="w-full text-left text-gray-400">
                            <thead className="bg-gray-900 text-gray-200 uppercase text-xs">
                                <tr>
                                    <th className="px-6 py-3">Nome</th>
                                    <th className="px-6 py-3">Usuário</th>
                                    <th className="px-6 py-3">Tipo</th>
                                    <th className="px-6 py-3 text-right">Ações</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-700">
                                 {adminUsers.map((admin) => (
                                    <tr key={admin.id} className="hover:bg-gray-700/50">
                                        <td className="px-6 py-4 font-medium text-white">{admin.name}</td>
                                        <td className="px-6 py-4">{admin.username}</td>
                                        <td className="px-6 py-4">
                                            <span className={`px-2 py-1 rounded text-xs ${admin.role === 'master_admin' ? 'bg-purple-900/50 text-purple-300' : 'bg-gray-700 text-gray-300'}`}>
                                                {admin.role === 'master_admin' ? 'Master Admin' : 'Admin'}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            {admin.id !== '00000000-0000-0000-0000-000000000000' && admin.id !== currentUserId && ( // Prevent actions on initial placeholder if any, though ID check handles logic
                                                <>
                                                    <button 
                                                        onClick={() => startEditAdmin(admin)}
                                                        className="text-gray-400 hover:text-white mr-3" 
                                                        title="Editar Administrador"
                                                    >
                                                        <i className="fas fa-edit"></i>
                                                    </button>
                                                    <button 
                                                        onClick={() => requestDeleteAdmin(admin)}
                                                        className="text-red-400 hover:text-red-300" 
                                                        title="Excluir Administrador"
                                                    >
                                                        <i className="fas fa-trash"></i>
                                                    </button>
                                                </>
                                            )}
                                        </td>
                                    </tr>
                                 ))}
                            </tbody>
                        </table>
                    </div>
                 </div>

                 {/* Modal: New/Edit Admin Form */}
                 {showAdminForm && (
                     <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
                         <div className="bg-gray-800 rounded-lg shadow-2xl border border-gray-600 w-full max-w-md">
                             <div className="px-6 py-4 border-b border-gray-700 bg-gray-900 rounded-t-lg">
                                 <h3 className="text-xl font-bold text-white">
                                     {editingAdmin ? 'Editar Administrador' : 'Adicionar Novo Administrador'}
                                 </h3>
                             </div>
                             <form onSubmit={handleAdminSubmit} className="p-6 space-y-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-400 mb-1">Nome</label>
                                    <input 
                                        type="text" 
                                        required
                                        className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                        value={adminForm.name}
                                        onChange={(e) => setAdminForm({...adminForm, name: e.target.value})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-400 mb-1">Usuário</label>
                                    <input 
                                        type="text" 
                                        required
                                        className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                        value={adminForm.username}
                                        onChange={(e) => setAdminForm({...adminForm, username: e.target.value})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-400 mb-1">Senha</label>
                                    <input 
                                        type="text" 
                                        required
                                        className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                        value={adminForm.password}
                                        onChange={(e) => setAdminForm({...adminForm, password: e.target.value})}
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-400 mb-1">Função</label>
                                    <select 
                                        className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                                        value={adminForm.role}
                                        onChange={(e) => setAdminForm({...adminForm, role: e.target.value as 'admin' | 'master_admin'})}
                                    >
                                        <option value="admin">Administrador (Comum)</option>
                                        <option value="master_admin">Administrador Master</option>
                                    </select>
                                </div>
                                 <div className="flex justify-end gap-3 mt-6">
                                     <button 
                                        type="button" 
                                        onClick={() => setShowAdminForm(false)}
                                        className="px-4 py-2 rounded bg-gray-700 text-gray-300 hover:bg-gray-600"
                                     >
                                         Cancelar
                                     </button>
                                     <button type="submit" className="px-4 py-2 rounded bg-purple-600 text-white font-bold hover:bg-purple-500">
                                         {editingAdmin ? 'Atualizar' : 'Adicionar'}
                                     </button>
                                 </div>
                             </form>
                         </div>
                     </div>
                 )}
             </div>
        )}

      </main>

      {/* Delete Confirmation Modal */}
      {deleteConfirmation && (
          <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-[60] flex items-center justify-center p-4">
              <div className="bg-gray-800 rounded-lg shadow-2xl border border-red-600 w-full max-w-md animate-fade-in">
                  <div className="px-6 py-4 border-b border-gray-700 bg-gray-900 rounded-t-lg flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-red-900/50 flex items-center justify-center">
                          <i className="fas fa-exclamation-triangle text-red-500"></i>
                      </div>
                      <h3 className="text-xl font-bold text-white">Confirmar Exclusão</h3>
                  </div>
                  <div className="p-6">
                      <p className="text-gray-300 text-lg mb-2">
                          Você tem certeza que deseja excluir 
                          <span className="font-bold text-white"> {deleteConfirmation.name || 'este item'}</span>?
                      </p>
                      
                      {deleteConfirmation.type === 'company' && (
                          <div className="bg-red-900/20 border border-red-800 p-3 rounded text-sm text-red-300 mb-4">
                              <i className="fas fa-info-circle mr-2"></i>
                              Atenção: Isso também excluirá todos os funcionários e contracheques associados a esta empresa.
                          </div>
                      )}

                      {deleteConfirmation.type === 'admin' && (
                          <div className="bg-red-900/20 border border-red-800 p-3 rounded text-sm text-red-300 mb-4">
                              <i className="fas fa-user-slash mr-2"></i>
                              Esta ação revogará o acesso administrativo deste usuário permanentemente.
                          </div>
                      )}
                      
                      <p className="text-gray-500 text-sm">Esta ação não pode ser desfeita.</p>
                  </div>
                  <div className="px-6 py-4 bg-gray-900/50 rounded-b-lg flex justify-end gap-3">
                      <button 
                          onClick={() => setDeleteConfirmation(null)}
                          className="px-4 py-2 rounded bg-gray-700 text-gray-300 hover:bg-gray-600 transition-colors"
                      >
                          Cancelar
                      </button>
                      <button 
                          onClick={handleConfirmDelete}
                          className="px-4 py-2 rounded bg-red-600 text-white font-bold hover:bg-red-500 shadow-lg transition-colors flex items-center"
                      >
                          <i className="fas fa-trash mr-2"></i> Excluir Definitivamente
                      </button>
                  </div>
              </div>
          </div>
      )}
      
      {/* Password Change Modal */}
      {showPasswordModal && (
          <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-[70] flex items-center justify-center p-4">
              <div className="bg-gray-800 rounded-lg shadow-2xl border border-gray-600 w-full max-w-md">
                  <div className="px-6 py-4 border-b border-gray-700 bg-gray-900 rounded-t-lg">
                      <h3 className="text-xl font-bold text-white">Trocar Minha Senha</h3>
                  </div>
                  <form onSubmit={handleChangePasswordSubmit} className="p-6 space-y-4">
                      <div>
                          <label className="block text-sm font-medium text-gray-400 mb-1">Nova Senha</label>
                          <input 
                              type="password" 
                              required
                              className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                              value={newPassword}
                              onChange={(e) => setNewPassword(e.target.value)}
                              placeholder="Digite a nova senha"
                          />
                      </div>
                      <div>
                          <label className="block text-sm font-medium text-gray-400 mb-1">Confirmar Nova Senha</label>
                          <input 
                              type="password" 
                              required
                              className="w-full bg-gray-700 border border-gray-600 rounded p-2 text-white"
                              value={confirmPassword}
                              onChange={(e) => setConfirmPassword(e.target.value)}
                              placeholder="Confirme a nova senha"
                          />
                      </div>
                      <div className="flex justify-end gap-3 mt-6">
                          <button 
                              type="button" 
                              onClick={() => {
                                  setShowPasswordModal(false);
                                  setNewPassword('');
                                  setConfirmPassword('');
                              }}
                              className="px-4 py-2 rounded bg-gray-700 text-gray-300 hover:bg-gray-600"
                          >
                              Cancelar
                          </button>
                          <button type="submit" className="px-4 py-2 rounded bg-green-600 text-white font-bold hover:bg-green-500">
                              Atualizar Senha
                          </button>
                      </div>
                  </form>
              </div>
          </div>
      )}

    </div>
  );
};

export default AdminDashboard;
